### ISSUE TITLE
matrix.lua fails to load due to lua error

### ISSUE THREAD

**Issue by paanvaannd** [torhve/weechat-matrix-protocol-script#102]
The following error shows upon starting weechat after installing the plugin via the README instructions:
> lua: unable to execute file "/home/pan/.weechat/lua/autoload/matrix.lua"
> lua: error: /home/pan/.weechat/lua/autoload/matrix.lua:46: module 'cjson' not found:
> no field package.preload['cjson']
> no file './cjson.lua'
> no file '/usr/local/share/lua/5.1/cjson.lua'
> no file '/usr/local/share/lua/5.1/cjson/init.lua'
> no file '/usr/local/lib/lua/5.1/cjson.lua'
> no file '/usr/local/lib/lua/5.1/cjson/init.lua'
> no file '/usr/share/lua/5.1/cjson.lua'
> no file '/usr/share/lua/5.1/cjson/init.lua'
> no file './cjson.so'
> no file '/usr/local/lib/lua/5.1/cjson.so'
> no file '/usr/lib/x86_64-linux-gnu/lua/5.1/cjson.so'
> no file '/usr/lib/lua/5.1/cjson.so'
> no file '/usr/local/lib/lua/5.1/loadall.so'

System: Ubuntu 17.10 (Artful Aardvark)

any help on how to resolve this would be appreciated!

**Comment by erdnaxeli** [comment]
You need the cjson lua package.

**Comment by paanvaannd** [comment]
Thanks! :+)
