### ISSUE TITLE
Autoload README error

### ISSUE THREAD

**Issue by helmi77** [torhve/weechat-matrix-protocol-script#111]
I think the following line in the readme is incorrect:
```
ln -s ~/.weechat/lua/matrix.lua ~/.weechat/lua/autoload
```
Shouldn't there be a trailing slash after `autoload`?

**Comment by louib** [comment]
@helmi77 you're right, and this was fixed in https://github.com/torhve/weechat-matrix-protocol-script/pull/138 !
