### ISSUE TITLE
How to disable it

### ISSUE THREAD

**Issue by lindhe** [torhve/weechat-matrix-protocol-script#121]
Sorry for the trivial question, but I really can not figure this out: how do I disable the matrix script? I try to just close the buffers like with other servers and rooms, but it reappears the next time I start weechat...

**Comment by weechatter** [comment]
Like any other script in WeeChat, see /help script or /help lua

or remove symlink from ~./weechat/lua/autoload folder.

**Comment by lindhe** [comment]
Removing the symlink did it for me. `/help lua` presented no way for me to disable autoload (apparently only to enable autoload).
