### ISSUE TITLE
script: plugin "lua" is not loaded

### ISSUE THREAD

**Issue by Amolith** [torhve/weechat-matrix-protocol-script#131]
WeeChat is running on a Debian VPS. I downloaded the plugin, copied it to `~/.weechat/lua/` and made the symlink into `autoload/`. I opened my tmux session with WeeChat inside, ran `/plugin load matrix.lua` and got the following error: `script: plugin "lua" is not loaded`.

I've since installed `lua-cjson` per the README and restarted WeeChat but I'm still getting the same error.

**Comment by ReadWriteError** [comment]
I had this issue too there is a missing dep. For me (on debian testing/buster) it was fixed by running `sudo apt install weechat-lua`.

**Comment by Amolith** [comment]
That fixed it; thank you so much!
