### ISSUE TITLE
Prefix mapping is kind of wonky

### ISSUE THREAD

**Issue by Xe** [torhve/weechat-matrix-protocol-script#15]
`#ponydevs:matrix.org` assigns people a power level of 25 out of the gate, there's no `+` prefixed to people's messages.

**Comment by torhve** [comment]
I gave a user power level 25 and tested, works fine here. What more can I do to reproduce?

**Comment by Xe** [comment]
try a channel with a default level of 25?

**Comment by torhve** [comment]
Okay, pushed a fix for this. Thanks for letting me know, never seen such a room before :-)
