### ISSUE TITLE
Does not work on OS X

### ISSUE THREAD

**Issue by fladd** [torhve/weechat-matrix-protocol-script#18]
The instructions are not correct.

`sudo port install weechat +lua` will install Lua 5.3

But the script expects 5.2 it seems.

The result is that it will simply not load.

**Comment by ara4n** [comment]
Back when this was written, macports installed lua 5.2. as a result the suggested lua environment exports pointed at 5.2. have updated the readme to reflect 5.3 and spell out you may need to manually specify the right version.  tested as working on latest macports & yosemite.

**Comment by torhve** [comment]
Thanks for the update. I will close this issue as the readme is updated to reflect the current situation.
