### ISSUE TITLE
Script spams core buffer with "Error: buffer not found"

### ISSUE THREAD

**Issue by vberger** [torhve/weechat-matrix-protocol-script#22]
At startup, and then more or less regularly while running (not necessarily while I'm interacting with weechat), the script floods my core weechat buffer with messages like

```
00:34:55 	<=!=>	Error: buffer not found
00:34:55 	<=!=>	Error: buffer not found
00:34:55 	<=!=>	Error: buffer not found
01:00:20 	<=!=>	Error: buffer not found
01:00:20 	<=!=>	Error: buffer not found
01:00:20 	<=!=>	Error: buffer not found
```

I'm using weechat 1.4, connected to my homeserver running synapse v0.12.0, and without the olm.lua script.

I can try to get more information about what's going on (it's sure these are not very informative error messages), but I don't know where to look.

**Comment by vberger** [comment]
Okay, it comes from some kind of bad interaction with the script `autosort.py`.

If I try to load this script after `matrix.lua` is loaded, it just spawns one such error and does not sort anything.

**Comment by torhve** [comment]
I think that error is weechat telling a script that the script used an API command on a buffer that weechat can't find. Maybe there's a bug in autosort, that it doesn't handle the weird names of the marix buffers, like buffers with spaces in the name, or other differences from straight up IRC names.

**Comment by vberger** [comment]
Yep, probably. The feedback I had from #weechat on freenode was mainly "don't use autosort"...

Anyway, probably not a bug from here actually. :smile:

**Comment by torhve** [comment]
Thank you for reporting it anyway, so the next guy that comes along sees this and gets helped.
