### ISSUE TITLE
Plugin causes `/quit` to freeze weechat

### ISSUE THREAD

**Issue by mitchhentges** [torhve/weechat-matrix-protocol-script#24]
This only happens on my laptop, and not on my desktop. Both are Arch linux, with weechat `1.4`.
Version of `weechat-matrix-protocol-script` are identical.
If I remove `weechat-matrix-protocol-script`, then `/quit` works properly

[lua.matrix.weechatlog.txt](https://github.com/torhve/weechat-matrix-protocol-script/files/129247/lua.matrix.weechatlog.txt)
[weechat.log.txt](https://github.com/torhve/weechat-matrix-protocol-script/files/129248/weechat.log.txt)

If I can provide any other logging information, let me know. I'm here to help :)

**Comment by torhve** [comment]
I think it's a WeeChat problem, linked to this bug: https://github.com/weechat/weechat/issues/406

**Comment by mitchhentges** [comment]
Ok, awesome, glad that it's already being taken care of :)
I'm not sure if you'd prefer to keep this issue open or not, but I'm ok with it being closed

**Comment by torhve** [comment]
I will keep it open until it's fixed in WeeChat.

**Comment by torhve** [comment]
This has been fixed in WeeChat
