### ISSUE TITLE
Message pane is 1 column wide.

### ISSUE THREAD

**Issue by vext01** [torhve/weechat-matrix-protocol-script#29]
Not sure why this has suddenly happened, but the message pane is now one column wide in matrix windows only.

![weechat](https://cloud.githubusercontent.com/assets/604955/15613920/d465012c-242d-11e6-8cd0-dd00e4573aa8.png)

**Comment by torhve** [comment]
My guess is that you changed the settings for how bars in weechat can grow and shrink, and someone has a very long nick. I don't think this is related to matrix.lua, unless you have more information for me.

**Comment by vext01** [comment]
You are right. Someone has an insanely long username.

Fixed with `/set weechat.bar.nicklist.size 20`

**Comment by vext01** [comment]
And `/set weechat.look.prefix_align_max 10`
