### ISSUE TITLE
URL not printed after file upload

### ISSUE THREAD

**Issue by firecat53** [torhve/weechat-matrix-protocol-script#31]
Hey, I was impressed that the file upload worked great! It just doesn't print the upload URL in the chat buffer to show that the upload was completed successfully. If I leave and then rejoin, it is visible, but it'd be nice to have that feedback when the upload completes.

Thanks!
Scott

**Comment by torhve** [comment]
Ah. There is an issue here with local_echo setting in matrix.lua, which I don't use personally. (I enjoy seeing the latency on the synapse server delivery).

Thanks for noticing and reporting this.
