### ISSUE TITLE
Unable to connect to matrix homeservers with self-signed certificate (default for synapse)

### ISSUE THREAD

**Issue by proycon** [torhve/weechat-matrix-protocol-script#44]
Curl rightly complains about the certificate if it is self-signed, but it would be nice if there were an option to override this:

```
matrix: Unable to load olm encryption library. Not enabling encryption. Please see documentation (README.md) for information on how to
matrix: Connecting to homeserver URL: https://anaproy.nl:8448
error: curl error 60 (server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none) (URL: "https://anaproy.nl:8448_matrix/client/r0/login")
```

**Comment by regnarg** [comment]
Can be worked around by a simple modification to the `http` function in `matrix.lua`:
~~~~.diff
diff --git a/matrix.lua b/matrix.lua
index 5dcc712..1b89752 100644
--- a/matrix.lua
+++ b/matrix.lua
@@ -431,6 +431,8 @@ local function http(url, post, cb, timeout, extra, api_ns)
     if not extra then
         extra = nil
     end
+    post.pinnedpublickey = "/PATH/TO/SERVER.tls.crt"
+    post.ssl_verifypeer = 0
     if not api_ns then
         api_ns = "_matrix/client/r0"
     end
~~~~
Where the `SERVER.tls.crt` should be the public certificate copied from your homeserver's `.synapse` directory.

**Comment by maxidor** [comment]
Seeing more and more users attempting this, 8448 is not designed for clients.

You should either:
- Use 8008 but is HTTP only
- Reverse proxy 443 to 8008 and provide a valid certificate (e.g. Let's encrypt)

Source: [synapse README](https://github.com/matrix-org/synapse#using-a-reverse-proxy-with-synapse)
> The recommended setup is therefore to configure your reverse-proxy on port 443 for client connections, but to also expose port 8448 for server-server connections.
>
> [... nginx config ...]
>
> You will also want to set bind_addresses: ['127.0.0.1'] and x_forwarded: true for port 8008 in homeserver.yaml to ensure that client IP addresses are recorded correctly.

**Comment by regnarg** [comment]
I have a reverse proxy from 443, but (1) I'm too lazy to setup letsencrypt, (2) I don't trust CAs so I want a pinned cert anyway.
