### ISSUE TITLE
Crash when connecting

### ISSUE THREAD

**Issue by jcrawfordor** [torhve/weechat-matrix-protocol-script#53]
When connecting to a Matrix homeserver, Weechat sits after the "matrix: Connecting to homeserver..." output for some seconds and then crashes.

**Crash Output**

> (written by WeeChat 1.0.1, compiled on Sep 28 2014 15:54:55)
> 001  ??:? [function weechat_backtrace]
> 002  ??:? [function debug_sigsegv]
> 003  ??:? [function __restore_rt]
> 004  /build/glibc-daoqzt/glibc-2.19/string/../sysdeps/x86_64/strlen.S:106 [function strlen]
> addr2line: '0x397e6': No such file
> addr2line: '0x39bb5': No such file
> 007  ??:? [function hook_info_get]
> addr2line: '0x123b4': No such file
> addr2line: '0xc1f0': No such file
> addr2line: '0x16d42': No such file
> addr2line: '0xc64d': No such file
> addr2line: '0xb92e': No such file
> addr2line: '0xc7bb': No such file
> addr2line: '0x842c': No such file
> addr2line: '0x19118': No such file
> addr2line: '0xc1f0': No such file
> addr2line: '0x16d42': No such file
> addr2line: '0xc64d': No such file
> addr2line: '0xb92e': No such file
> addr2line: '0xc7bb': No such file
> addr2line: '0x842c': No such file
> addr2line: '0x7cd2': No such file
> addr2line: '0x9a36': No such file
> 024  ??:? [function hook_process_send_buffers]
> 025  ??:? [function hook_process_timer_cb]
> 026  ??:? [function hook_timer_exec]
> 027  ??:? [function gui_main_loop]
> 028  ??:? [function main]
> ^[5029  /build/glibc-daoqzt/glibc-2.19/csu/libc-start.c:321 [function __libc_start_main]
> 030  ??:? [function _start]

[Full backtrace](https://gist.github.com/jcrawfordor/a96dc482a402613681a55f4728786715)

I don't know much if anything about debugging Lua plugins, so let me know what other info I can provide.

**Comment by jcrawfordor** [comment]
Weechat version is 1.0.1. I'm not necessarily adverse to having to build a newer version, but if this problem is resolvable under 1.0.1 that'd be nice.

**Comment by torhve** [comment]
I would advise to upgrade, there has been many bugs fixed in weechat that was discovered during development of this script.

**Comment by jcrawfordor** [comment]
Can confirm an identical configuration is working properly now that I've built weechat 1.6. I'll close this as "vague old version problems." thx
