### ISSUE TITLE
Add option to disable the sending of read receipts

### ISSUE THREAD

**Issue by Gwend4l** [torhve/weechat-matrix-protocol-script#96]
It would be great to have a simple option to disable the sending of read receipts.

In the meantime, is it documented which lines to change/comment to disable sending these receipts?

thanks!

**Comment by erdnaxeli** [comment]
You can comment the ligne 1315. This will still move your read marker, but disable the send receipt.

I will add an option for that.

**Comment by gurucubano** [comment]
In this context: Can we have an option too so the other side is not seeing 'user is typing'? Thanks
